version: "3"
services:
  nginx-proxy:
    container_name: ${PROJECT_NAME}-nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  webserver:
    container_name: ${PROJECT_NAME}-webserver
    image: nginx:latest
    volumes:
      - .:/var/www/${PROJECT_NAME}
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=${PROJECT_NAME}.localhost
    expose:
      - "80"

  php-fpm:
    container_name: ${PROJECT_NAME}-php-fpm
    image: harbor.picturae.com/php/picturae-php${PHP_VERSION}:1.0.0
    environment:
      - VIRTUAL_HOST=${PROJECT_NAME}-php-fpm.localhost
      - COMPOSER_AUTH=${COMPOSER_AUTH}
    volumes:
      - .:/var/www/${PROJECT_NAME}
      - ./docker/php-fpm/php-fpm.d:/etc/php/${PHP_VERSION}/fpm/pool.d
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/${PHP_VERSION}/fpm/conf.d/99-overrides.ini
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/${PHP_VERSION}/cli/conf.d/99-overrides.ini
    working_dir: /var/www/${PROJECT_NAME}

  mysql:
    container_name: ${PROJECT_NAME}-mysql
    image: mariadb:10.3.27
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - VIRTUAL_HOST=${PROJECT_NAME}-mysql.localhost
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "8983"

  node:
    container_name: ${PROJECT_NAME}-node
    image: harbor.picturae.com/node/picturae-node${NODE_VERSION}
    environment:
      - VIRTUAL_HOST=${PROJECT_NAME}-node.localhost
    volumes:
      - .:/var/www/${PROJECT_NAME}
    working_dir: /var/www/${PROJECT_NAME}
    ports:
      - "35729:35729"
    tty: true

volumes:
  mysql:
    driver: local
